// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function DownloadModels() {
  return window['go']['main']['App']['DownloadModels']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function OnHide() {
  return window['go']['main']['App']['OnHide']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
