// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CloseSettings():Promise<void>;

export function DownloadModels():Promise<void>;

export function GetSettings():Promise<core.AppSettings>;

export function GetThumbnail(arg1:string):Promise<string>;

export function OnHide():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function RebuildIndex():Promise<void>;

export function SaveSettings(arg1:core.AppSettings):Promise<void>;

export function Search(arg1:string):Promise<Array<core.SearchResult>>;
