// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetThumbnail(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<Array<core.SearchResult>>;
